version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - CACHE_SIZE=`du -sh /root/.npm | cut -f1`
      - echo "Cache size is $CACHE_SIZE"
      - FUNCTION_NAME=${function_name}
      - CURRENT_VERSION=`aws lambda list-versions-by-function --function-name ${function_name} --query "Versions[-1]" | jq -r .Version`
      - echo $CURRENT_VERSION
      - TARGET_VERSION=$((CURRENT_VERSION+1))
      - conf/generateAppSpec.sh > src/appspec.yml
  build:
    commands:
      - cd src
      - npm install
      - zip -r ../terraform/payload.zip .
  post_build:
    commands:
      - CACHE_SIZE=`du -sh /root/.npm | cut -f1`
      - echo "Cache size is $CACHE_SIZE"
artifacts:
  base-directory: terraform
  files: 
    - '**/*'
cache:
  paths:
    - '/root/.npm/**/*'